### ISSUE TITLE
devtools::check_win_release(): Error in curl_fetch_memory

### ISSUE THREAD

**Issue by SavaryGraph** [r-lib/devtools#2249] opened 2020-07-16 09:42 UTC
Hi everyone,

I obtain an error when checking an R package (graph4lg) with devtools::check_win_release():
Error in curl::curl_fetch_memory(url, handle = h) : 
  Failed FTP upload: 550

It works fine with devtools::check_win_devel().

I have seen that it is a frequent issue, without being able to find a solution in my case.
Is it due to a temporary problem on the network, or should I change something in the way I check the package?

Thank you in advance 
I hope this issue is not redundant

**Comment by jimhester** [comment] 2020-07-16 12:48
This is a duplicate of https://github.com/r-lib/devtools/issues/2248, please search open issues before posting.

**Closed by jimhester** 2020-07-16 12:48 UTC

**Comment by SavaryGraph** [comment] 2020-07-16 13:00
Thank you for your answer.
I checked and only found other older issues about this subject, without
seeing this one. I apologize for that.

Regards
Paul Savary

Le jeu. 16 juil. 2020 à 14:49, Jim Hester <notifications@github.com> a
écrit :
