### ISSUE TITLE
System2 error

### ISSUE THREAD

**Issue by GBeattie** [r-lib/devtools#2134] opened 2019-10-15 14:40 UTC
Hey!
Getting the following error message when trying to install the package "loomR", any assistance greatly appreciated! 

```
> devtools::install_github(repo = "mojaveazure/loomR", ref = "develop")
Downloading GitHub repo mojaveazure/loomR@develop
✔  checking for file ‘/private/var/folders/ll/jmydhb6n7jqg5rv_c58jxkkh0000gn/T/RtmpV9Trlp/remotes5812b133b82/mojaveazure-loomR-1eca16a/DESCRIPTION’ ...
   Error in system2("cp", "--version", stdout = TRUE, stderr = FALSE) : 
     error in running command
   Execution halted
   sh: rm: command not found
Error: Failed to install 'loomR' from GitHub:
  System command error, exit status: 1, stdout + stderr:
E> * checking for file ‘/private/var/folders/ll/jmydhb6n7jqg5rv_c58jxkkh0000gn/T/RtmpV9Trlp/remotes5812b133b82/mojaveazure-loomR-1eca16a/DESCRIPTION’ ... OK
E> Error in system2("cp", "--version", stdout = TRUE, stderr = FALSE) : 
E>   error in running command
E> Execution halted
E> sh: rm: command not found
```

**Comment by jimhester** [comment] 2019-10-16 12:45
It seems that package assumes you have command line tools on your PATH. You may need to either install the Xcode command line tools or (re)approve the license for them.

In any case this is not a bug in devtools, so I will close this issue. 

If you have further problems this sort of question is a better fit for <https://community.rstudio.com>. Do you mind asking it over there? (You might want to read <https://www.tidyverse.org/help/> first to maximise your chances of getting a good answer)

**Closed by jimhester** 2019-10-16 12:45 UTC
