### ISSUE TITLE
Error in getOption("repos")[["CRAN"]] : subscript out of bounds

### ISSUE THREAD

**Issue by adamhsparks** [r-lib/devtools#2297] opened 2020-11-15 09:08 UTC
Seemingly a duplicate of this issue that I cannot comment on: https://github.com/r-lib/devtools/issues/1956.

Exactly the same behaviour is exhibited. I get the same error message when I try to use `devtools::release()` after the third step.

```r
Error in getOption("repos")[["CRAN"]] : subscript out of bounds
```

But if, as per the locked issue, I set 

```r
options(repos = list(CRAN = "http://cran.us.r-project.org"))
```

it works as expected. I tried installing the version from GitHub as well and it exhibits the same unexpected behaviour.

**Comment by jimhester** [comment] 2020-11-16 13:43
Please provide the results of `traceback()` after the error.

**Comment by hongooi73** [comment] 2020-11-17 09:05
Technically speaking, `repos` is supposed to be a _named_ vector with the names specifying what type of repo each URL is. However, most code still works with an unnamed vector, so people tend to forget the naming requirement.

**Comment by adamhsparks** [comment] 2020-11-17 09:17
Thanks @hongooi73. That’s probably it. I was sloppy. I will check. 🤔

**Comment by adamhsparks** [comment] 2020-11-17 09:24
Well, they are named in my .Rprofile. 

```r
   repos = structure(
      c(CSIRO = "https://cran.csiro.au/",
        UNIMELB = "https://cran.ms.unimelb.edu.au/")
   )
```

However, I just tried it with a different package (that is not on CRAN yet) and everything was fine, or seemed to be. I didn't follow through to submission.

Here's the traceback with `bomrang`, which is on CRAN and causes the error.

```r
8: cran_url()
7: paste0(cran_url(), "/web/checks/check_results_", pkg, ".html")
6: url_pkg_res(pkg)
5: read_cran_web_from_pkg(pkg, ...)
4: cran_results_web(email, pkg, ...)
3: foghorn::cran_results(pkg = pkg, show = c("error", "fail", "warn", 
       "note"))
2: has_cran_results(pkg$package)
1: devtools::release()
```

**Comment by jimhester** [comment] 2020-11-17 13:47
The names matter, you do need to have one named `CRAN`, or an unnamed vector of length 1.

It also seems that from the traceback the issue is in foghorn, not devtools, so I am going to close this issue.

**Closed by jimhester** 2020-11-17 13:47 UTC
