### ISSUE TITLE
`devtools::release()` breaks with unicode characters in `tempdir()` path

### ISSUE THREAD

**Issue by mikolajsp** [r-lib/devtools#2508] opened 2023-03-24 10:04 UTC
Hello,

I've encountered an issue with the devtools::submit_cran() function. I would like to mention at the beginning, that I'm not sure if the problem is in the `devtools` package, or in some dependency like `httr`.

I'm working in a Windows environment, and my username has a unicode character in it, specifically "ł". For this reason, the default Windows temporary directory

### Replication of the issue:

1. Set the system environment variable TMPDIR to a path containing the character "ł", in my case it is `C:\Users\Mikołaj\AppData\Local\Temp`

2. Try to release something to CRAN

### Workaround:

Set the TMPDIR to a path without Unicode characters e.g. `C:\temp`

**Comment by jennybc** [comment] 2023-03-24 15:50
Possibly a duplicate of #2422 

I would need to see more specifics to know for sure (a reprex, including session info), but I suspect the root problem might be one of the known issues in fs, such as https://github.com/r-lib/fs/issues/383.

**Comment by jennybc** [comment] 2023-11-02 21:52
This thread seems to have gone cold.

**Closed by jennybc** 2023-11-02 21:52 UTC
Labels: reprex
