### ISSUE TITLE
"Would you like to update?" the yes/no options should be in a consistent place

### ISSUE THREAD

**Issue by daattali** [r-lib/devtools#1997] opened 2019-02-21 21:37 UTC
Whenever I install a github package with install_github, I am presented with something like:

```
These packages have more recent versions available.
Which would you like to update?

1:   BH         (1.66.0-1 -> 1.69.0-1) [CRAN]
2:   colorspace (1.3-2    -> 1.4-0   ) [CRAN]
3:   later      (0.7.5    -> 0.8.0   ) [CRAN]
4:   R6         (2.3.0    -> 2.4.0   ) [CRAN]
5:   rlang      (0.3.0.1  -> 0.3.1   ) [CRAN]
6:   CRAN packages only
7:   All
8:   None
```

Let's say I want to update all, so I choose 7.
Next I install another package, and it only has 2 dependencies that can be updated, so now I have to choose 4.

It's a lot of friction to have to scan through the output and choose the right number, and seems like unnecessary adding slowness to the process. I strongly feel that the "CRAN", "All", "None" options should always have the same way to choose them, whether it be 1-2-3 or maybe even "C" "A" "N". Perhaps there's a good argument to doing it the current way that I don't see!

**Comment by jimhester** [comment] 2019-02-21 21:44
This is basically a duplicate of https://github.com/r-lib/remotes/issues/287

**Closed by jimhester** 2019-02-21 21:44 UTC
