### ISSUE TITLE
Installation:  cannot fall back to source packages if binary is not available

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/devtools#1724] opened 2018-02-28 14:24 UTC
E.g. happens on R-devel often, even with prominent packages like data.table.

I think devtools should only override the option, if it not set by the user already, via either the option or the env var.

**Comment by jimhester** [comment] 2018-02-28 16:13
Are you talking about the following? https://github.com/r-lib/devtools/blob/3068e654770d18be4e2a626c30300a95f9e50c32/R/deps.R#L321-L324

I would love to have a better way to make sure `install.packages()` install binaries if they are available and falls back to source if not (without prompting for user input), but both this and the previous method used seem to have various issues https://github.com/r-lib/devtools/blob/64a4791f78416d2623c5963715b56ef5077c5cee/R/deps.R#L52-L55

I think the method currently used seems to install packages from source in some case even when there is a binary available, which is the cause of https://github.com/r-lib/devtools/issues/1605

If you can think of a better way to do this it would be great!

**Comment by jimhester** [comment] 2018-02-28 16:14
Oh, so devel devtools does not overwrite the type option, but as I said above this approach also has issues of its own.

**Comment by gaborcsardi** [comment] 2018-02-28 16:40
> Are you talking about the following?

yes.

> I think the method currently used seems to install packages from source in some case even when there is a binary available

I don't see how that is possible. Maybe if the user explicitly sets the type to source, but then that's the desired behavior?

**Comment by jimhester** [comment] 2018-02-28 18:40
The behavior I have observed in devel devtools is dependencies being compiled from source even when there are binaries available and `getOption(pkgType) == "both"`. And it is fixed by explicitly passing type = "binary" to `install_()`

**Comment by gaborcsardi** [comment] 2018-02-28 19:18
pkgman fixes this eventually, but it would be nice to reproduce it, nevertheless. "both" works well in remotes:
```
setting R_COMPILE_AND_INSTALL_PACKAGES to always
> remotes::install_local('tidyhydat',dependencies=TRUE,INSTALL_opts='--build')
Installing 64 packages: assertthat, backports, base64enc, BH, bindr, bindrcpp, bit, bit64, blob, cli, colorspace, crayon, curl, DBI, dbplyr, dichromat, digest, dplyr, evaluate, ggplot2, glue, gtable, highr, hms, htmltools, httr, jsonlite, knitr, labeling, lazyeval, lubridate, magrittr, markdown, memoise, mime, munsell, openssl, pillar, pkgconfig, plogr, plyr, praise, purrr, R6, rappdirs, RColorBrewer, Rcpp, readr, reshape2, rlang, rmarkdown, rprojroot, RSQLite, scales, stringi, stringr, testthat, tibble, tidyr, tidyselect, utf8, viridisLite, withr, yaml
Warning: unable to access index for repository http://www.stats.ox.ac.uk/pub/RWin/bin/windows/contrib/3.5:
  cannot open URL 'http://www.stats.ox.ac.uk/pub/RWin/bin/windows/contrib/3.5/PACKAGES'
Package which is only available in source form, and may need
  compilation of C/C++/Fortran: 'tidyselect'
package 'assertthat' successfully unpacked and MD5 sums checked
package 'backports' successfully unpacked and MD5 sums checked
package 'base64enc' successfully unpacked and MD5 sums checked
package 'BH' successfully unpacked and MD5 sums checked
package 'bindr' successfully unpacked and MD5 sums checked
...
```

**Comment by dracodoc** [comment] 2018-03-13 14:16
@jimhester The behavior you mentioned is exactly [what I observed (with CRAN version, not just devel devtools)](https://stackoverflow.com/questions/48995314/how-to-make-devtools-install-github-to-install-dependency-packages-from-cran-ins)

- When installing a package with `devtools::install_github`, dependency packages were installed from source in github, even when there is binary available in CRAN.
- And the problem was made worse because of the bug of sha not checked, every dependency package was compiled again and again in every install (not skipped when I have that same version installed)

My finding is that because the dependency package is installed by `install_github` before, the local package description file has the github remote information, and devtools will take that and install from github. Reinstall that dependency package from CRAN will solve the problem.

Specifying `binary` in package install doesn't solve this problem because we often want to install some packages from source. I think the `both` option in `install.packages` strike a good balance in this
- binary was tried if both are available, in same version
- ask user whether to install source if source is newer
- there is option to skip the prompt

**Comment by dracodoc** [comment] 2018-03-13 14:22
I also found `remotes` is working well in this case. 

Maybe `devtools` can pick a `remotes` commit, delegate related tasks to `remotes` (it could be hard because other parts may need some newer functions, but this should be done sooner than later), then gradually apply the new changes in `devtools` side to `remotes`. At least that will be work in single direction.

**Comment by jimhester** [comment] 2018-03-13 18:53
> because the dependency package is installed by install_github before, the local package description file has the github remote information, and devtools will take that and install from github

This is the intended behavior, if you have a devel version of a package installed it should update the package to the latest devel version, not install a binary.

**Comment by dracodoc** [comment] 2018-03-13 18:59
Yes, think again I agree that behavior is actually reasonable. 

Previously I was frustrated because `httpuv` take a long time to compile and fail every time, and every of my installation need to go through that again (and several other packages can compile but take time, but were installed again because of the sha checking bug).

**Comment by jimhester** [comment] 2018-03-13 19:12
So github disabled support for SSLv1 connections at the end of February https://githubengineering.com/crypto-removal-notice/, which broke `git2r::remote_ls()` to GitHub, so you now always get an NA result from GitHub repositories and the error message you observed. e.g.

``` r
git2r::remote_ls("https://github.com/r-lib/devtools.git")
#> Error in git2r::remote_ls("https://github.com/r-lib/devtools.git"): Error in 'git2r_remote_ls': SSL error: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
```

Created on 2018-03-13 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

I will have to investigate to see if we can specify a later protocol for `remote_ls()` or if not think about an alternative way to get the current SHA, perhaps with the GitHub API.

**Comment by jimhester** [comment] 2018-03-13 21:31
The SSL v1 issue is fixed by https://github.com/r-lib/devtools/commit/21fe55a912ca4eaa49ef5b7d891ff3e2aae7a370

**Closed** 2018-07-18 12:59 UTC
Labels: bug
