### ISSUE TITLE
devtools::release Error in !dr_d : invalid argument type

### ISSUE THREAD

**Issue by tbates** [r-lib/devtools#2108] opened 2019-09-10 14:02 UTC
Under `packageVersion("devtools") ‘2.2.0.9000’`, running `release()`  yields an error. 

```R
devtools::release()
Error in !dr_d : invalid argument type
In addition: Warning message:
'dr_devtools' is deprecated.
Use 'dev_sitrep()' instead.
See help("Deprecated") and help("devtools-deprecated"). 
```
`traceback` is empty

I got the same error with CRAN `devtools`

R version: R version 3.6.1 (2019-07-05)
Platform: x86_64-apple-darwin15.6.0 
MacOS: 10.14.6

**Comment by jimhester** [comment] 2019-09-10 19:30
This is a duplicate of https://github.com/r-lib/devtools/issues/2105, it is fixed in the devel version

**Closed by jimhester** 2019-09-10 19:30 UTC
