### ISSUE TITLE
Error at first installation with install_github

### ISSUE THREAD

**Issue by kamapu** [r-lib/devtools#1978] opened 2019-01-24 09:00 UTC
I try to install a package form GitHub using `devtools`

```r
library(devtools)
install_github("kamapu/spatialist")
```
and got an error message

    Error in read.dcf(path) : 
    Found continuation line starting '	person("Miguel", "A ...' at begin of record.

If I use `CMD INSTALL` or `install_local()`, the installation will work fine.

At the beginning I though, the problem is because the package has only one function, which may not be a common case, but I realized that this issue also appears with other packages when I install for the very first time, and not when updating installed packages.

May this be a bug?

**Comment by kamapu** [comment] 2019-02-05 09:44
still having this problem within my colleagues...

**Comment by simongrund1** [comment] 2019-02-05 15:08
Can confirm this. Fresh install after an update to 3.5.2 on Windows with no other external packages installed besides `devtools`. The full set of commands run right after the install were:
```r
install.packages("devtools")
install_github("stefvanbuuren/mice")
```
This gave the error:
```
Error in read.dcf(path) :
  Found continuation line starting '    email = "stef. va ...' at begin of record.
```
Note that this is a different package. It's also interesting that I was able to run the same command without problem on an older install of R version 3.5.1 (also on Windows).

**Comment by simongrund1** [comment] 2019-02-05 15:40
This solves the problem for me. Specifically, I needed to:

1. Run `devtools::install_github("r-lib/remotes")`
2. Restart R.
3. Run `devtools::install_github("...")` for the intended package.

Doing this, all packages install as intended. Thanks for the quick feedback!

**Comment by jennybc** [comment] 2019-02-05 15:43
OK great, so this is a duplicate of #1900.

**Closed by jennybc** 2019-02-05 15:43 UTC
