### ISSUE TITLE
source_gist fails when not specifying filename

### ISSUE THREAD

**Issue by meowcat** [r-lib/devtools#1751] opened 2018-04-03 15:33 UTC
My gist has only one file which is a .R file, so I thought specifying filename shouldn't be necessary? And anyway it should source the first file according to documentation. However it fails with "invalid subscript type closure", I guess because "which" is never set and actually refers to the R function "which" instead.

```R
source_gist("cf98b8f3f78c2b1e4dd9337e3cfb511c") 
# Error in r_files[[which]] : invalid subscript type 'closure'
source_gist("cf98b8f3f78c2b1e4dd9337e3cfb511c", filename="fixLumosMzXml.R") 
#  Sourcing https://gist.githubusercontent.com/meowcat/cf98b8f3f78c2b1e4dd9337e3cfb511c/raw/889c4bec1d451141b177875c619dab09fff00454/fixLumosMzXml.R 
# SHA-1 hash of file is c2df39528ab774eaec3d5d717e792eaa7bb96faa
```

**Comment by jimhester** [comment] 2018-07-17 17:37
This is a duplicate of https://github.com/r-lib/devtools/issues/1266 and is fixed by cb86ae45434d

**Closed by jimhester** 2018-07-17 17:37 UTC
Labels: bug
