### ISSUE TITLE
`devtools` is breaking in Travis

### ISSUE THREAD

**Issue by cimentadaj** [r-lib/devtools#2021] opened 2019-04-10 06:38 UTC
I recently got a Travis build error from the new devtools version from a package that has been building just fine for the past year. Here's the error:

![image](https://user-images.githubusercontent.com/8180025/55856774-97ec8800-5b6b-11e9-90ba-0c5f6c8b22a7.png)

from [this](https://travis-ci.org/cimentadaj/perccalc?utm_medium=notification&utm_source=email) package

I also see some other people having exactly the same error [here](https://twitter.com/apreshill/status/1115611962002403328)

**Comment by jimhester** [comment] 2019-04-10 12:25
This is a duplicate of https://github.com/r-lib/devtools/issues/2020, you need to delete your travis cache so that remotes v2.0.3 is used. You can do so within the travis UI, https://docs.travis-ci.com/user/caching/#clearing-caches has the details.

**Closed by jimhester** 2019-04-10 12:25 UTC
