### ISSUE TITLE
`devtools::document()` trips on `setMethod` whose function definition is empty

### ISSUE THREAD

**Issue by ramiromagno** [r-lib/devtools#1984] opened 2019-02-05 22:17 UTC
Running

```r
devtools::document(roclets=c('rd', 'collate', 'namespace'))
```

on a package that I am developing (gwasrapidd) that contains this code:

```r
#' @param object An object
#' @param data Numeric vector or data.frame
#' @param Fun Function. Default function is \code{sum}
#' @param ... Extra named arguments passed to FUN
#' @rdname myGeneric
#' @export
setGeneric("myGeneric", function(object, data, FUN, ...)
{standardGeneric ("myGeneric")} )

#' @rdname myGeneric
setMethod("myGeneric", c("numeric", "numeric", "function"),
          function(object, data, FUN, ...) {
            #return(42)
            }
          )
```

Gives this error:

```
> devtools::document(roclets=c('rd', 'collate', 'namespace'))
Updating gwasrapidd documentation
Loading gwasrapidd
Error in method_body[[2]] : subscript out of bounds
```
If I uncomment `#return(42)` making that function not empty then `devtools::document` runs without errors.

I am using these package versions:

- devtools_1.13.6
- roxygen2_6.1.1

My question is: is this intended behaviour or is it a bug? (and not, I don't need empty functions, just wondering :) )

NB: I just started writing S4 methods, therefore I was not sure I was documenting generic functions and methods correctly so I started by asking about this problem in stackoverflow: https://stackoverflow.com/questions/54540540/why-does-devtoolsdocument-trip-on-setmethod-whose-function-definition-is.

**Comment by ramiromagno** [comment] 2019-02-06 13:49
See this issue too: https://github.com/klutometis/roxygen/issues/843

**Comment by jimhester** [comment] 2019-02-11 22:06
Closing this as it is not a bug in devtools, but in roxygen.

**Closed** 2019-02-11 22:06 UTC
